# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ExcelTable' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExcelTable
	pod 'Masonry'	
	pod 'JKCategories'
  target 'ExcelTableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExcelTableUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
